coin/urls.py
from django.apps import apps
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from coin import views
import coin.apps

from django.contrib import admin
admin.autodiscover()

from coin.isp_database.views import isp_json
import coin.members.views


def apps_urlpatterns():
    """ Yields url lists ready to be appended to urlpatterns list
    """
    for app_config in apps.get_app_configs():
        if isinstance(app_config, coin.apps.AppURLs):
            for prefix, pats in app_config.exported_urlpatterns:
                yield path(
                    f'{prefix}/',
                    include(pats, namespace=prefix))

urlpatterns = [
    #'',
    path('', coin.members.views.index, name='home'),

    path('isp.json', isp_json),
    path('members/', include('coin.members.urls', namespace='members')),
    path('billing/', include('coin.billing.urls', namespace='billing')),
    path('subscription/', include('coin.offers.urls', namespace='subscription')),
    path('admin/', admin.site.urls),
    path('hijack/', include('hijack.urls', namespace='hijack')),

    # path('admin/doc/', include('django.contrib.admindocs.urls')),

    path('feed/<feed_name>', views.feed, name='feed'),

    path('autocomplete/', include('autocomplete_light.urls')),
]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Pluggable apps URLs
urlpatterns += list(apps_urlpatterns())


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

vpn/urls.py
from django.conf.urls import url

from .views import VPNView, VPNGeneratePasswordView, get_graph

app_name = "vpn"
urlpatterns = [
    #'',
    # This is part of the generic configuration interface (the "name" is
    # the same as the "backend_name" of the model).
    url(r'^(?P<pk>\d+)$', VPNView.as_view(template_name="vpn/vpn.html"), name="details"),
    url(r'^password/(?P<pk>\d+)$', VPNGeneratePasswordView.as_view(template_name="vpn/fragments/password.html"), name="generate_password"),
    url(r'^graph/(?P<vpn_id>[0-9]+)/(?P<period>[a-z]+)$', get_graph, name="get_graph"),
    url(r'^graph/(?P<vpn_id>[0-9]+)$', get_graph, name="get_graph"),
]

vps/urls.py
from django.conf.urls import url

from .views import VPSView

app_name = 'vps'
urlpatterns = [
    #'',
    # This is part of the generic configuration interface (the "name" is
    # the same as the "backend_name" of the model).
    url(r'^(?P<pk>\d+)$', VPSView.as_view(template_name="vps/vps.html"), name="details"),
]

vps/models.py
from django.db import models
from polymorphic.models import PolymorphicModel
from django.core.exceptions import ValidationError
from django.urls import reverse
from netfields import InetAddressField, NetManager

from coin.configuration.models import IPConfiguration
from coin.offers.models import OfferSubscriptionRequest


FINGERPRINT_TYPES = (
    ('ED25519', 'ED25519'),
    ('RSA', 'RSA'),
    ('ECDSA', 'ECDSA')
)

PROTOCOLE_TYPES = (
    ('VNC', 'VNC'),
)

import struct
import base64
def PublicSSHKeyValidator(ssh_pubkey):
    if not isinstance(ssh_pubkey, str):
        raise ValidationError("Une clef SSH devrait être une chaine de caractères?")
    try:
        # From https://stackoverflow.com/questions/2494450/ssh-rsa-public-key-validation-using-a-regular-expression
        type_, key_string, comment = ssh_pubkey.strip().split(None, 2)
        data = base64.decodestring(key_string)
        int_len = 4
        str_len = struct.unpack('>I', data[:int_len])[0] # this should return 7
        data[int_len:int_len+str_len] == type_
    except:
        raise ValidationError("Il semblerait qu'il y ai une erreur de syntaxe dans cette clef SSH")


class VPSOperatingSystem(models.Model):

    reference = models.CharField(max_length=64,
                                 blank=False, null=False,
                                 verbose_name="Nom technique (utilisé par les scripts)")

    display_name = models.CharField(max_length=128, verbose_name="Nom affiché aux êtres humains",
                                    blank=False, null=False)

    def __unicode__(self):
        return self.display_name

    class Meta:
        verbose_name = 'Système d\'exploitation'
        verbose_name_plural = 'Systèmes d\'exploitation'
        app_label = "vps"


class VPSProvisioningParameters(models.Model):

    operating_system = models.ForeignKey(VPSOperatingSystem, blank=True, null=True,
            on_delete=models.CASCADE)

    ssh_key = models.TextField(max_length=1024, verbose_name="Clef SSH",
                               blank=True, null=True,
                               validators=[PublicSSHKeyValidator])

    class Meta:
        abstract = True
        app_label = "vps"

class VPSConfiguration(IPConfiguration, VPSProvisioningParameters):

    url_namespace = "vps"

    # Subclasses can fill this list with stuff like "operating_system" or "ssh_key" or "password"
    provisioning_infos = ["operating_system", "ssh_key"]

    def get_absolute_url(self):
        return reverse('vps:details', args=[str(self.pk)])

    def __unicode__(self):
        return 'VPS ' + str(self.offersubscription.member.username) + ' ' + self.offersubscription.member.last_name

    class Meta:
        verbose_name = 'VPS'
        app_label = "vps"

class FingerPrint(PolymorphicModel):
    vps = models.ForeignKey(VPSConfiguration, verbose_name="vps",
            on_delete=models.CASCADE)
    algo = models.CharField(max_length=256, verbose_name="algo",
                            choices=FINGERPRINT_TYPES)
    fingerprint = models.CharField(max_length=256, verbose_name="empreinte")
    length = models.IntegerField(verbose_name="longueur de la clé", null=True)

    class Meta:
        verbose_name = 'Empreinte'
        app_label = "vps"


class Console(models.Model):
    vps = models.OneToOneField(VPSConfiguration, verbose_name="vps",
            on_delete=models.CASCADE)
    protocol = models.CharField(max_length=256, verbose_name="protocole",
                            choices=PROTOCOLE_TYPES)
    domain = models.CharField(max_length=256, verbose_name="nom de domaine",
                                blank=True, null=True)
    port = models.IntegerField(verbose_name="port", null=True)
    password_link = models.URLField(verbose_name="Mot de passe", blank=True,
                           null=True, help_text="Lien à usage unique (détruit après ouverture)")
    class Meta:
        verbose_name = 'Console'
        app_label = "vps"


class VPSSubscriptionRequest(OfferSubscriptionRequest, VPSProvisioningParameters):

    configuration_class = VPSConfiguration

    class Meta:
        verbose_name = 'demande de VPS'
        verbose_name_plural = 'demandes de VPS'
        app_label = "vps"

vps/forms.py
from django import forms

from coin.offers.forms import OfferSubscriptionRequestStep2Form
from .models import VPSOperatingSystem, VPSSubscriptionRequest, PublicSSHKeyValidator


class VPSSubscriptionRequestStep2Form(OfferSubscriptionRequestStep2Form):

    offer_type = "VPS"
    subscriptionrequest_class = VPSSubscriptionRequest

    operating_system = forms.ModelChoiceField(queryset=VPSOperatingSystem.objects.all(), label="Système d'exploitation", required=True)
    ssh_key = forms.CharField(label="Clef SSH", max_length=1024, widget=forms.Textarea(attrs={'style': 'height: 10em;'}), required=True, validators=[PublicSSHKeyValidator])

    def create_offersubscriptionrequest(self, request):
        subscriptionrequest = super().create_offersubscriptionrequest(request)
        subscriptionrequest.operating_system = self.cleaned_data["operating_system"]
        subscriptionrequest.ssh_key = self.cleaned_data["ssh_key"]
        return subscriptionrequest

vps/views.py
from django.shortcuts import get_object_or_404
from django.views.generic.edit import UpdateView
from django.conf import settings
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from coin.members.models import Member

from .models import VPSConfiguration
from .forms import VPSSubscriptionRequestStep2Form # We need to load this even if we don't actually use it ... but otherwise the code ain't loaded at all in django for some reason :|


class VPSView(SuccessMessageMixin, UpdateView):
    model = VPSConfiguration
    fields = ['ipv4_endpoint', 'ipv6_endpoint', 'comment']
    success_message = "Configuration enregistrée avec succès !"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_form(self, form_class=None):
        if settings.MEMBER_CAN_EDIT_VPS_CONF:
            return super().get_form(form_class)
        return None

    def get_object(self):
        if self.request.user.is_superuser:
            return get_object_or_404(VPSConfiguration, pk=self.kwargs.get("pk"))
        # For normal users, ensure the VPS belongs to them.
        return get_object_or_404(VPSConfiguration, pk=self.kwargs.get("pk"),
                                 offersubscription__member=self.request.user)

vps/templates/vps/vps.html
{% extends "base.html" %}
{% load subnets %}
{% block content %}
<div class="row">

    <div class="col-12">
    <h2>{{ object.get_state_icon_display }} {{ object }}</h2>
    </div>

    <div class="col-12">
    <div class="card my-2">
    <h3 class="card-header">État</h3>
    <table class="table mb-0">
        <tbody>
            <tr>
                <td>Offre</td>
                <td>{{ object.offersubscription.offer }}</td>
            </tr>
            <tr>
                <td>Status</td>
                <td>{{ object.get_state_icon_display }} {{ object.get_state_text_display }} <small>(Dernière mise à jour : {{ object.last_status_update }})</small></td>
            </tr>
            <tr>
                <td>Commentaire</td>
                <td>{{ object.comment }}</td>
            </tr>
            <tr>
                <td>IPv4</td>
                <td>{{ object.ipv4_endpoint|prettify }}</td>
            </tr>
            <tr>
                <td>IPv6</td>
                <td>{{ object.ipv6_endpoint|prettify }}</td>
            </tr>
            <tr>
                <td>Sous-réseaux</td>
                <td>
                    {% for subnet in object.ip_subnet.all %}{{ subnet }}<br/>{% endfor %}
                </td>
            </tr>
        </tbody>
    </table>
    </div>
    </div>

    <div class="col-12">
    <div class="card my-2">
    <h3 class="card-header">Accès</h3>
    <table class="table mb-0">
        {% if object.fingerprint_set.all %}
        <tr>
            <td>Empreinte(s)</td>
            <td>
                {% for fingerprint in object.fingerprint_set.all %}
                {{ fingerprint.length }} {{ fingerprint.fingerprint }} ({{ fingerprint.algo }}){% if not forloop.last %}<br />{% endif %}
                {% endfor %}
            </td>
        </tr>
        {% endif %}
        {% if object.console %}
        <tr>
            <td>Console {{object.console.protocol}}</td>
            <td>
                {{ object.console.domain }}:{{ object.console.port }}<br />
                <a href="{{object.console.password_link}}">Voir le mot de passe (lien supprimé après ouverture)</a>
            </td>
        </tr>
        {% endif %}
    </table>
    </div>
    </div>

    {% if object.offersubscription.offer.infos %}
    <div class="col-12">
    <div class="card my-2">
    <h3 class="card-header">Informations complémentaires de l'équipe bénévole</h3>
    <div class="card-body">
        {{ object.offersubscription.offer.infos|safe }}
    </div>
    </div>
    </div>
    {% endif %}
</div>

{% endblock %}